services:
  app:
    container_name: ros2log

    build:
      context: .
      dockerfile: docker/Dockerfile

    ports:
      - "5000:5000"

    volumes:
      - ./storage:/storage

    extra_hosts:
      - "host.docker.internal:host-gateway"

    logging:
      driver: local
      options:
        max-size: "20m"
        max-file: "5"

    healthcheck:
      test: ["CMD", "python", "-c", "import config, urllib.request; urllib.request.urlopen(f'http://localhost:{config.SERVER_PORT}/health')"]
      interval: 300s
      timeout: 3s
      retries: 3
      start_period: 5s

    restart: unless-stopped

  ros2:
    profiles: ["development"]

    build:
      context: .
      dockerfile: docker/ros2.Dockerfile

    volumes:
      - ./storage:/storage

    restart: unless-stopped
